# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      # Git
      - id: check-merge-conflict
      # Secrets
      - id: detect-aws-credentials
      - id: detect-private-key
      # Generic file state
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace

  # Front-end settings
  # htmlhint
#  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
#    rev: v1.1.2
#    hooks:
#      - id: htmlhint
#        files: ^src/front-end/src

  # Back-end settings
  # pycln -> isort -> black -> pylint -> django -> pre-commit-hooks -> django-test
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.2.5 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
      - id: pycln
        name: Remove unused import statements
        language: python
        language_version: python3
        files: ^src/back-end/
        types: [python]
        exclude: ^.*\b(migrations)\b.*$
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Sort import statements
        files: ^src/back-end/
        types: [python]
        exclude: ^.*\b(migrations)\b.*$
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      -  id: black
         language: system
         files: ^src/back-end/
         types: [python]
         exclude: ^.*\b(migrations)\b.*$
         args: ["--line-length=120", "--target-version=py39"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        files: ^src/back-end/web/
        types: [python]
        exclude: ^.*\b(migrations)\b.*$
        args:
          - --rcfile=src/back-end/web/.pylintrc
          - --max-line-length=120
          - --disable=R0903,C0103,W0703,E1101,W0613,W0511,R0201,E5110,R0801
  - repo: https://github.com/ecugol/pre-commit-hooks-django
    rev: v0.4.0
    hooks:
      - id: check-untracked-migrations
        files: ^src/back-end/
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
        files: ^src/back-end/
        types: [json]
      - id: pretty-format-json
        files: ^src/back-end/
        types: [json]
      - id: trailing-whitespace
        files: ^src/back-end/
      - id: debug-statements
        files: ^src/back-end/
      - id: check-merge-conflict
        files: ^src/back-end/
      - id: detect-aws-credentials
        files: ^src/back-end/
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
        files: ^src/back-end/
      - id: end-of-file-fixer
        files: ^src/back-end/
      - id: name-tests-test
        exclude: ^.*\b(migrations)\b.*$
        args: ["--django"]

  # Deploy Settings
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.14.3
    hooks:
      - id: check-github-actions
        files: ^.github/actions/
      - id: check-github-workflows
        files: ^.github/workflows/
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.1.0
    hooks:
      - id: docker-compose-check
