name: close-of-milestones
on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        * * * * *
    - cron:  '0 0 * * SAT' # midnight of every Saturday

jobs:
  milestones:
    runs-on: ubuntu-latest
    environment: version-management
    name: Milestone Closer
    steps:
    - name: Close milestones that are past-due and have zero open issues.
      uses: MrGossett/github-action-milestone-closer@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
